# Рабочая роль может управлять только очередями и обменником проекта.
default_user_tags.management = true
default_permissions.configure = ^payments\.(new|dlq|dead|events)$
default_permissions.write = ^payments\.(new|dlq|dead|events)$
default_permissions.read = ^payments\.(new|dlq|dead|events)$
max_message_size = 65536
log.console.level = warning
